### PR TITLE
Security fix: Use random_bytes() instead of uniqid()

### PR DESCRIPTION
**Pull request by JuliusPC**
**This security fix will break compatibility with PHP versions prior to 7.0. But in my opinion, it doesn't matter since these are End-of-Life since more than a year. Anyway, including [random_compat](https://github.com/paragonie/random_compat) may be a solution.**

[RFC 6749](https://tools.ietf.org/html/rfc6749#section-10.12) recommends CSRF protection via `state` parameter. Therefore, its value needs to be cryptographically secure ([uniqid](https://php.net/uniqid) does not provide that). The [OIDC-Spec](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes) states the same for `nonce`:

> The nonce parameter value needs to include per-session state and be unguessable to attackers. One method to achieve this for Web Server Clients is to store a _cryptographically random value_ as an HttpOnly session cookie and use a cryptographic hash of the value as the nonce parameter.

**List of common tasks a pull request require complete**
- [x] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Comment by jumbojett** [comment]
@JuliusPC I like this. Can we make it backwards compatible by calling the appropriate function based on if it exists? It's also worth noting that the method can be overridden by the developer since it's `protected`.

**Comment by JuliusPC** [comment]
@jumbojett Using `uniqid()` is not appropriate -- even for backward compatibility. Is PHP < 7.0 really needed? If this is the case I would add [random_compat](https://github.com/paragonie/random_compat) library which does the job by choosing an appropriate method to generate secure random and thus providing a fallback for `random_bytes`.

**Comment by jumbojett** [comment]
>  Is support for PHP < 7.0 really needed?

I want to ensure legacy apps depending on our library aren't alienated.

> If this is the case I would add random_compat library which does the job by choosing an appropriate method to generate secure random and thus providing a fallback for random_bytes.

@JuliusPC This sounds like the right path. I appreciate your insight and expertise! If you could add this to your PR, I'd be happy to merge it.

**Comment by JuliusPC** [comment]
I added `random_compat`. It therefore should not be a breaking change any more. I didn’t ran any tests on legacy versions of php. `random_comat` itselfs seems to work.

Once this path is merged, you should tag a new release since `uniqid()` renders CSRF protection almost useless.

**Comment by JuliusPC** [comment]
Any news on this?

**Comment by JuliusPC** [comment]
@jumbojett Any news on this?

**Comment by jumbojett** [comment]
@JuliusPC Thank you for the PR and following up on this! I really appreciate it.

**Comment by JuliusPC** [comment]
@jumbojett How about a new release to ship this fix and PKCE support to users of this library? :)

**Comment by jumbojett** [comment]
@JuliusPC done 👍

**Pull request merged**
