### PR TITLE
Fix up signatures

### LINKED ISSUE #412: Return types are too strict
#327 introduced several return types that are too strict. Some examples,

Sometimes an identity provider will return an opaque access token. When an attempt is made to `json_decode` the JWT, `null` is returned. This gives the following exception when an attempt is made to retrieve the access token payload (seen when authenticating with Google):

`TypeError: Return value of Jumbojett\OpenIDConnectClient::decodeJWT() must be an instance of stdClass, null returned
Backtrace:
from /var/www/mediawiki/w/extensions/OpenIDConnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(1231)
#0 /var/www/mediawiki/w/extensions/OpenIDConnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(1751): Jumbojett\OpenIDConnectClient->decodeJWT()
#1 /var/www/mediawiki/w/extensions/OpenIDConnect/includes/OpenIDConnect.php(306): Jumbojett\OpenIDConnectClient->getAccessTokenPayload()`

Sometimes an identity provider will not return a refresh token. In this case, $this->refreshToken is never changed from the default value of `null`. This gives the following exception when an attempt is made to retrieve the refresh token (seen when authenticating with Microsoft):

`TypeError: Return value of Jumbojett\OpenIDConnectClient::getRefreshToken() must be of the type string, null returned
Backtrace:
from /var/www/mediawiki/w/extensions/OpenIDConnect/vendor/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(1732)
#0 /var/www/mediawiki/w/extensions/OpenIDConnect/includes/OpenIDConnect.php(323): Jumbojett\OpenIDConnectClient->getRefreshToken()`

### PR DESCRIPTION
**Pull request by hexmode**
Also add phpunit dependency, add test target, fix up phpunit.xml.dist, and add changelog entry.

Fixes #412

### CODE REVIEW

**Comment by osnard** [comment]
@DeepDiver1975 Can we please get this merged and released? This issue prevents me from updating production code to 1.x

**Comment by DeepDiver1975** [comment]
The hard dependency on phpunit causes issues to run ci on php 7.x .... please remove.

**Comment by hexmode** [comment]
> Generally speaking I'd prefer to have dedicated pull requests for dedicated topics/issues. Let's see what CI tells us and then we cut it into dedicated chunks.

I'll roll back all but my own changes here.

**Comment by hexmode** [comment]
fwiw, phpunit dep worked for me on php 7.4 just now but I've removed it as requested.

**Comment by hexmode** [comment]
Given the failures on php 7.0, the options are dropping support 7.0 (my preference, since it is EOL) or dropping the type hints.

**Comment by DeepDiver1975** [comment]
php7.0 compliant version https://github.com/jumbojett/OpenID-Connect-PHP/pull/427

**Pull request closed without merging**
