### PR TITLE
Add headers-params for requestResourceOwnerToken

### PR DESCRIPTION
**Pull request by BigTonni**
**List of common tasks a pull request require complete**
- [ ] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Comment by jumbojett** [comment]
@BigTonni Thanks for the PR! I have a question. Did you try the following before making the code change? It should perform the same flow except without encoding the credentials. I'm wondering if we just need to simply alter the method to base64 encode instead of posting the credentials unencoded.

```
//Add username and password
$oidc->addAuthParam(array('username'=>'<Username>'));
$oidc->addAuthParam(array('password'=>'<Password>'));

//Perform the auth and return the token (to validate check if the access_token property is there and a valid JWT) :
$token = $oidc->requestResourceOwnerToken(TRUE)->access_token;
```

**Comment by BigTonni** [comment]
@jumbojett I tested differently. For example, if User uses Password grant_type, his username/password and your original version of this method, then error code 401 is returned. But if user adds a Basic Authorization header, then user receives successful data. Access_token, token_type and other.

**Comment by jumbojett** [comment]
> if user adds a Basic Authorization header, then user receives successful data. Access_token, token_type and other.

@BigTonni Thanks for the insight! Should we unset the credentials in `$post_data` if an auth header is passed? 

```
        $post_data = array(
            'grant_type'    => $grant_type,
            'username'      => $this->authParams['username'], // unset?
            'password'      => $this->authParams['password'],  // unset?
            'scope'         => implode(' ', $this->scopes)
        );
```

**Comment by BigTonni** [comment]
@jumbojett No, you should not.
The custom request will look something like this:

$oidc = new OpenIDConnectClient('https://id.provider.com',
                                'ClientIDHere',
                                'ClientSecretHere');
$oidc->providerConfigParam(array('token_endpoint'=>'https://id.provider.com/connect/token'));
$oidc->addScope('my_scope');

//Add username and password
$oidc->addAuthParam(array('username'=>'<Username>'));
$oidc->addAuthParam(array('password'=>'<Password>'));

$headers = ['Authorization: Basic ' . base64_encode(.'ClientIDHere' .':'. 'ClientSecretHere'.)];
$token = $oidc->requestResourceOwnerToken(TRUE, $headers)->access_token;

**Comment by azmeuk** [comment]
This is covered by #271

**Pull request closed without merging**
