### PR TITLE
Strip port from host header when calculating redirect URL.

### PR DESCRIPTION
**Pull request by mrmorcs**
Proposed fix for issue: https://github.com/jumbojett/OpenID-Connect-PHP/issues/58

My first ever pull request, hope all correct!

### CODE REVIEW

**Comment by jumbojett** [comment]
> My first ever pull request, hope all correct!

Congrats @mrmorcs! 🎉 

> Strip port from host header

We might be able to simplify this PR due to the `$useport` variable already being present. Would something like this work?

```
$useport = ($protocol === 'https' && $port !== 443) || ($protocol === 'http' && $port !== 80);
```

to

```
$useport = ($protocol === 'https' && $port !== 443) || ($protocol === 'http' && $port !== 80) || !isset($_SERVER['HTTP_HOST']);
```

**Comment by mrmorcs** [comment]
Yeah I think so, will experiment and get back to you :+1:

**Comment by mrmorcs** [comment]
Hi @jumbojett 

It didn't feel right assigning the combined hostname and port into a variable called $hostname, so I've refactored it to use a variable called $host. Then I'm stripping the port if it's a default for the protocol afterwards.

Would this be OK?

**Comment by jumbojett** [comment]
@mrmorcs Thanks! Looks good. I work-shopped your PR and simplified some logic. Can you verify that it works for your scenario? (It should be replacing lines `338-381` ) If it does, make a final change to your PR and I'll accept it. That way you'll be listed as a contributor. :)

```php
        /*
         * Compatibility with multiple host headers.
         * The problem with SSL over port 80 is resolved and non-SSL over port 443.
         * Support of 'ProxyReverse' configurations.
         */

        $protocol = @$_SERVER['HTTP_X_FORWARDED_PROTO'] 
                  ?: @$_SERVER['REQUEST_SCHEME']
                  ?: ((isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on") ? "https" : "http");

        $port = @intval($_SERVER['HTTP_X_FORWARDED_PORT'])
              ?: @intval($_SERVER["SERVER_PORT"])
              ?: (($protocol === 'https') ? 443 : 80);
        
        $host = @explode(":", $_SERVER['HTTP_HOST'])[0]
              ?: @$_SERVER['SERVER_NAME']
              ?: @$_SERVER['SERVER_ADDR'];

        // Don't include port if it's 80 or 443 and the protocol matches
        $port = ($protocol === 'https' && $port === 443) || ($protocol === 'http' && $port === 80) ? '' : ':' . $port;
        
        return sprintf('%s://%s%s/%s', $protocol, $host, $port, @trim($_SERVER['REQUEST_URI'], '/'));
```

**Comment by mrmorcs** [comment]
Awesome - I've made those replacements and can confirm it still works in my test environment :+1:

**Comment by jumbojett** [comment]
Thanks @mrmorcs !

**Comment by genebean** [comment]
👍 Thanks for the good work you all!

**Pull request merged**
