### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kenguest**
Added "Contributing" section, requesting the changelog.md file be updated when PRs are merged.

### CODE REVIEW

**Comment by kenguest** [comment]
I think the point of a changelog file is to list the changes made between/in released versions of the code, not to list the changes that people want to be in the code...?

**Comment by rasodu** [comment]
That is right. This section will contain the changes are merged into the project but haven't been released yet. Look at the example https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md

Every pull request will add an entry to this unreleased section of the changelog file. We can simply change unreleased to a version number when we release the code.

**Comment by kenguest** [comment]
@rasodu That's done now - change things as you see fit!

**Comment by rasodu** [comment]
#80

**Pull request closed without merging**
