### PR TITLE
fix: correct aud check in verifyLogoutTokenClaims

### PR DESCRIPTION
**Pull request by melanger**
previously, when aud was correct, the in_array clause was evaluated but failed with an error (aud is not array),
so the verifyLogoutTokenClaims function returned false for a valid token

**List of common tasks a pull request require complete**
- [x] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Also bug fixes require a change log entry. Please add. THX a lot!

**Comment by melanger** [comment]
> Also bug fixes require a change log entry. Please add. THX a lot!

The changelog was not validating against [parse-a-changelog](https://github.com/cyberark/parse-a-changelog) i.e. not adhering to the [Keep a changelog](https://keepachangelog.com/en/1.1.0/) style. I fixed it so that it would validate and added an unreleased entry.

Please consider [semantic release](https://github.com/semantic-release/), it can automate changelog generation (from commit messages) so that contributors do not have to write changelog entries manually and resolve frequent conflicts.

**Comment by azmeuk** [comment]
If  `aud` claim is a string, but not equal to the client ID, the code would call `in_array` with a non-array variable. In that case the function just emits a warning and returns false. I don't know if this is an issue.
Else it looks good to me.

**Review by azmeuk — APPROVED** [review]

**Comment by azmeuk** [comment]
Actually this is a duplicate of #334. I am closing this one.

**Comment by melanger** [comment]
OK, I created https://github.com/jumbojett/OpenID-Connect-PHP/pull/358 with the changelog fix only

**Pull request closed without merging**
