### PR TITLE
Cast SERVER_PORT to integer

### PR DESCRIPTION
**Pull request by timsmid**
Resolves issue #403.

**List of common tasks a pull request require complete**
- [x] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Review by ricklambrechts — APPROVED** [review]

**Comment by bison92** [comment]
Hi @jumbojett  please merge this!

**Comment by Webbeh** [comment]
Bump

This fix works for me as well. It is required for NGINX which sends the `SERVER_PORT` as string and not int.

**Comment by DeepDiver1975** [comment]
Can you  rebase please? THX

**Comment by timsmid** [comment]
@DeepDiver1975 Done!

**Comment by nobleclem** [comment]
v1.0.1 seems to be missing this update.  Looks like the commit (1e85443) from on 9/5/2024 for #427 reverted the change.

**Pull request merged**
