### PR TITLE
Added userInfo response type check to handle signed and encrypted res…

### PR DESCRIPTION
**Pull request by ricklambrechts**
This pull request will add support for signed and/or encrypted UserInfo response.
https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.3.2

Added response contentType field to hold value of the latest content type
Added jweResponseHandler so the package user can set an handler to decrypt the JWE
Handle signed jwt response from user info endpoint

Added support for encrypted id_token.
According to the [docs](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation), it is possible that the id token is encrypted. I added additional code that will decrypt the id_token when it is an JWE.

**List of common tasks a pull request require complete**
- [x] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Comment by ricklambrechts** [comment]
@DeepDiver1975 do we want to use an interface or should we use a callback like in pr #322?

**Comment by DeepDiver1975** [comment]
My personal answer would be: 
protected function which has the default handling implemented (like doing nothing)
anybody who wants to have a different behavior could then sub class the client and add what ever implementation is desired.

Alternative would be to use a callback just like done in any other place - just to make sure we are not mixing too much concepts.

**Comment by ricklambrechts** [comment]
@DeepDiver1975 thanks. I updated the code

**Comment by teemukolehmainen-howspace** [comment]
Any chance of getting this merged in?

**Comment by apeisa** [comment]
@DeepDiver1975 this would be very helpful for us as well.

**Review by DeepDiver1975 — APPROVED** [review]

**Pull request merged**
