### PR TITLE
Fix LogoutToken verification for single value `aud` claims

### PR DESCRIPTION
**Pull request by osnard**
... and add UnitTests for `verifyLogoutTokenClaims`.

See https://github.com/jumbojett/OpenID-Connect-PHP/issues/333

**List of common tasks a pull request require complete**
- [x] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Review by azmeuk — APPROVED** [review]
LGTM

**Comment by arifulbd** [comment]
Could you please resolve this soon, LogoutToken verification is broken due to this.
@azmeuk @DeepDiver1975

**Comment by azmeuk** [comment]
@osnard can you please fix the CHANGELOG conflicts so we can merge this patch? :pray:

**Comment by osnard** [comment]
Done

**Pull request merged**
