### PR TITLE
Keycloack support proposal

### PR DESCRIPTION
**Pull request by jlallana**
Best regards. Before me nothing I apologize for my clumsy English. I'm using an automatic translator. My native language is Spanish.

I pass this request for integration with new functionality that aggregates my software to use based on a configuration file 'Keyclock' client.

Product 'Keycloack' is an identity server which supports 'openid-connect' as one of the authentication protocols. It uses a file called 'keycloack.json' which provides a compatible data structure with several based on 'Java' servers.

Just add new static methods in concepts of factories to initialize the class by using the parameters 'keycloack' as input.

I put the changes on a branch and not directly to master so you can review it.

### CODE REVIEW

**Comment by jlallana** [comment]
bump

**Comment by jumbojett** [comment]
@jlallana Thanks for the PR. 
1. Would this be better served as a class the inherits from the OpenIDConnectPHP client? (Maybe create a separate repo with it's own composer file)
2. There are a few misspellings. (KeyCloak is correct) I've noticed Keycloack and Keyclock appear in the source.

**Comment by jlallana** [comment]
Again I apologize for my poor English.

In my opinion, an inheritance only to overload a constructor, is excessive.

I did not to avoid the implications of maintaining a single repository for a function. but in that case you do not accept my changes will be my steps.

On the other hand, add support this functionality in your repository can attract more developers to the same two separately.

As for the misspelling, I apologize, I correct it soon.

**Comment by jumbojett** [comment]
> Again I apologize for my poor English.

@jlallana I understand you clearly. You're doing well!

> On the other hand, add support this functionality in your repository can attract more developers to the same two separately.

That's an attractive incentive. The goal of this repo is to present a simple library that focuses on the basic workflow. I'd prefer you to start an other repo that inherits the library for several reasons.

1) You can take ownership of the code and maintain PRs that are relevant to Keycloak.
2) There will be little chance of others submitting PRs relevant to OIDC basic to break Keycloak support.

Example:
I took a similar route when making a Wordpress plugin that supports OIDC login. (https://github.com/jumbojett/Wordpress-OpenID-Connect-Login)

Does this make sense?

**Pull request closed without merging**
