### PR TITLE
Travis PSR-2 tests

### PR DESCRIPTION
**Pull request by guss77**
As specified in issue #57 - added PSR-2 tests using Travis.

Notes:
- Currently, as the code is not PSR-2 compliant, this test fails - as can be seen here: https://travis-ci.org/guss77/OpenID-Connect-PHP .
- This PR depends on PR #88 . It can be made to be standalone if it is required.
- The test does not run on PHP 5.4, as we use Phing which deps on Symphony that requires 5.5. As 5.4 as well as 5.5 are EOLed anyway, I recommend increased the requirement to 5.6.
- The test is using PHP_CodeSniffer 2.9 because 3.0 is not working well under Phing, and - at least that version - doesn't seem to implement PSR-2 correctly and complains about valid things. I'm investigating.

### CODE REVIEW

**Comment by guss77** [comment]
Only error remaining is the `Each class must be in a file by itself` which is a different item on issue #57 's list, so I think we should address that in another PR.

**Comment by jumbojett** [comment]
This is looking great @guss77. You are welcome to merge it when you're ready.

**Comment by lordelph** [comment]
@guss77 would love to see this project updated to PSR-2, are you able to resolve the conflicts in this PR? I'd be happy to take this on if you've moved onto other stuff :)

**Comment by jumbojett** [comment]
> I'd be happy to take this on if you've moved onto other stuff :)
@lordelph Go for it! I'm excited to see what you come up with.

**Comment by lordelph** [comment]
I contacted @guss77 directly last week and he said he'll be more active soon, so if there's no movement on this in the next week or so I'll pick it up!

**Pull request closed without merging**
