### PR TITLE
Add implementation for Token Introspection 

### PR DESCRIPTION
**Pull request by DeepDiver1975**
https://tools.ietf.org/html/rfc7662

**List of common tasks a pull request require complete**
- [x] Changelog entry is added or the pull request don't alter library's functionality

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Currently testing this .....

**Comment by DeepDiver1975** [comment]
@jumbojett mind having a look? THX

**Comment by jumbojett** [comment]
@DeepDiver1975 Thanks for the PR! As part of the request could you add an example use case to the README?

**Comment by DeepDiver1975** [comment]
> As part of the request could you add an example use case to the README?

here we go ...

**Comment by DeepDiver1975** [comment]
Thx for merging

**Comment by jumbojett** [comment]
Your welcome! Thank you.

**Pull request merged**
